### ISSUE TITLE
Base class ctor returns outer scope when invoked from superclass

### ISSUE THREAD

**Issue by mortenhaahr** [overturetool/language#56]
##### Identification of the Originator
Name: Morten Haahr Kristensen
Email: mortenhaahrkristensen@gmail.com
Role: Master student at Aarhus University

##### Target of the request, defining the affected components of the language definition 
To implement a more flexible constructor delegation behavior that is more similar to other languages **or** a clarification on the motives behind the current implementation.

##### Motivation for the request
I am currently modeling chess where I use inheritance to model shared behavior among different piece types. I want to follow the DRY principles by avoiding code duplication. The current way constructor delegation works forces me to make weird workarounds.

##### Description of the request
Change the behavior of constructor delegation to not return from super class constructor.

###### Description of the modification
If the base class constructor is invoked from the super class it will return from the super class constructor. Any statements below the base class invocation will be ignored. I suggest changing this so that any statements below the invocation will be invoked.

###### benefits from the modification
It will allow for constructor delegation where logic is based on variables that the base class initializes. See example 1.
The behavior is more similar to other programming languages which will thereby make the learning curve easier for newcomers. See example 2. I believe the behavior is similar in other languages.

###### possible side effects
Breaking old code. Theoretically, there might be code looking like example 3.

#### Example 1 - Motivation for change:

```
class Piece
types
public Color = <white>|<black>;

instance variables
public color : Color;

operations
public Piece : Color ==> Piece
Piece(c) == color := c;

end Piece

class Pawn is subclass of Piece  
instance variables
public pawn_direction : int;

operations
public Pawn : Color ==> Pawn
Pawn(c) == (
    Piece(c); -- Returns from Pawn Ctor

    -- Currently: Statement below is not called.
    -- Suggestion: Call these statements as well
    pawn_direction := if color = <white> then 1 else -1;
);

end Pawn
```

#### Example 2 - C++ behavior
```cpp
class Pawn : public Piece {
  public:
  Pawn(Color c) : Piece(c) {
    // pawn_direction gets instantiated depending on color, which is instantiated in base class Ctor
    pawn_direction = color == Color::white ? 1 : -1;
  }
};
```

#### Example 3 - Code possibly breaking
```
public Super : bool ==> Super
Super(b) == (
    if b 
    then 
        Super()
    instance_variable = ...;
    ...;
);
```

**Comment by nickbattle** [comment]
Isn't this just because the constructor returns a value? The behaviour is the same in VDMJ and VDMTools. The block semantics in VDM (SL as well as PP) means that any statement that returns a value (usually an operation call) will exit the block with that value. So to avoid it here, you can use:
```
public Pawn : Color ==> Pawn
Pawn(c) == (
    let - = Piece(c) in
        pawn_direction := if color = <white> then 1 else -1;
);
```
That absorbs the superclass value and allows the subclass to complete the construction:
```
> p new Pawn(<white>)
= Pawn{#2, color:=<white>, pawn_direction:=1, Piece{#1, color:=<white>}}
Executed in 0.015 secs.

> p new Pawn(<black>)
= Pawn{#4, color:=<black>, pawn_direction:=-1, Piece{#3, color:=<black>}}
Executed in 0.007 secs. 
```
The block-returning semantics has been built into VDM since the very beginning, so we could not easily change that(!). There might be a case for making constructors a special case, but special cases aren't a good idea. Overall, there are several ugly aspects of object-orientation in VDM++ (and a paper available discussing them), but progress in changing this is slow, I'm afraid.

**Comment by nickbattle** [comment]
Just to remind everyone... this is the current state of the _thinking_ on the object oriented issues, with some proposed solutions, in VDM++. You'll notice that we haven't make much progress with this since 2009.

[VDM_OO_Issues_0.2.pdf](https://github.com/overturetool/language/files/9994751/VDM_OO_Issues_0.2.pdf)

**Comment by mortenhaahr** [comment]
Hi Nick, thanks for the elaboration. I couldn't think of a workaround and therefore considered it a defect but you are absolutely right with your observation. I will close the issue.
